
excluded:
- Wack/SupportingFiles
- Pods

whitelist_rules:
- colon
- closure_end_indentation
- closure_parameter_position
- comma
- closure_spacing
- empty_count
- control_statement
- empty_parentheses_with_trailing_closure
- compiler_protocol_init
- cyclomatic_complexity
- discouraged_direct_init
- empty_parameters
- explicit_init
- fatal_error_message
- file_length
- first_where
- for_where
- force_try
- force_unwrapping
- function_body_length
- function_parameter_count
- generic_type_name
- implicit_getter
- implicit_return
- implicitly_unwrapped_optional
- joined_default_parameter
- large_tuple
- leading_whitespace
- legacy_cggeometry_functions
- legacy_constant
- legacy_constructor
- line_length
- mark
- multiline_parameters
- multiple_closures_with_trailing_closure
- number_separator
- object_literal
- opening_brace
- operator_usage_whitespace
- operator_whitespace
- overridden_super_call
- private_over_fileprivate
- prohibited_super_call
- protocol_property_accessors_order
- redundant_discardable_let
- redundant_nil_coalescing
- redundant_optional_initialization
- redundant_void_return
- return_arrow_whitespace
- shorthand_operator
- single_test_class
- statement_position
- switch_case_on_newline
- syntactic_sugar
- trailing_comma
- trailing_newline
- trailing_semicolon
- trailing_whitespace
- type_body_length
- type_name
- unneeded_parentheses_in_closure_argument
- unused_closure_parameter
- unused_enumerated
- unused_optional_binding
- valid_ibinspectable
- vertical_parameter_alignment
- vertical_parameter_alignment_on_call
- vertical_whitespace
- weak_delegate
- xctfail_message
- sorted_first_last
- sorted_imports
- override_in_extension
- yoda_condition
- discouraged_optional_boolean

colon:
  severity: error

closure_end_indentation:
  severity: error

closure_parameter_position:
  warning: 20
  error: 25
  severity: error

comma:
  severity: error

discouraged_direct_init:
  severity: error

closure_spacing:
  severity: error

empty_count:
  warning: 20
  error: 30
  severity: warning

control_statement:
  severity: warning

compiler_protocol_init:
  severity: warning

empty_parentheses_with_trailing_closure:
  severity: error

cyclomatic_complexity:
  warning: 54
  error: 60

discouraged_direct_init:
  severity: warning

empty_parameters:
  severity: error

explicit_init:
  severity: error

fatal_error_message:
  severity: error

file_length: 800

first_where:
  severity: warning

for_where:
  severity: warning

force_try:
  severity: warning

force_unwrapping:
  severity: error

function_body_length:
- 100 # warning
- 101 # error

function_parameter_count: 7

generic_type_name:
  severity: error

implicit_getter:
  severity: warning

implicit_return:
  severity: warning

implicitly_unwrapped_optional:
  warning: 190
  error: 200
  severity: warning

joined_default_parameter:
  severity: error

large_tuple: 6

leading_whitespace:
  severity: error

legacy_cggeometry_functions:
  severity: error

legacy_constant:
  severity: error

legacy_constructor:
  severity: error

line_length:
  warning: 200
  error: 500
  ignores_comments: true

mark:
  severity: warning

multiline_parameters:
  severity: warning

multiple_closures_with_trailing_closure:
  severity: warning

number_separator:
  severity: warning

object_literal:
  warning: 25
  error: 26
  severity: error

opening_brace:
  severity: error

operator_usage_whitespace:
  severity: error

operator_whitespace:
  severity: error

overridden_super_call:
  severity: warning

private_over_fileprivate:
  severity: warning

prohibited_super_call:
  severity: warning

protocol_property_accessors_order:
  severity: error

redundant_discardable_let:
  severity: error

redundant_nil_coalescing:
  severity: error

redundant_void_return:
  severity: error

return_arrow_whitespace:
  severity: error

shorthand_operator:
  severity: warning

single_test_class:
  severity: error

statement_position:
  severity: error

switch_case_on_newline:
  severity: warning

syntactic_sugar:
  severity: warning

trailing_comma:
  severity: error

trailing_newline:
  severity: warning

trailing_semicolon:
  severity: error

trailing_whitespace:
  severity: warning

type_body_length: 1_000

type_name:
  min_length: 3
  max_length: 60
  excluded:
    - DP
    - Row
    - Add
    - All
    - Tab
    - Pop
    - At

unneeded_parentheses_in_closure_argument:
  severity: warning

unused_closure_parameter:
  severity: warning

unused_enumerated:
  severity: warning

unused_optional_binding:
  severity: warning

valid_ibinspectable:
  severity: warning

vertical_parameter_alignment:
  warning: 18
  error: 19
  severity: error

vertical_parameter_alignment_on_call:
  warning: 55
  error: 56
  severity: warning

vertical_whitespace:
  severity: warning

weak_delegate:
  severity: warning

xctfail_message:
  severity: error

sorted_first_last:
  severity: warning

sorted_imports:
  severity: warning

override_in_extension:
  severity: error

yoda_condition:
  severity: warning

discouraged_optional_boolean:
  severity: warning
